name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      context_path:
        required: true
        type: string
      DOCKERHUB_USER:
        required: true
        type: string
      DOCKERHUB_PASS:
        required: true
        type: string
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build Docker image for ${{ inputs.service_name }}
      run: |
        docker build -f ${{ inputs.dockerfile_path }} -t ${{ inputs.DOCKERHUB_USER }}/${{ inputs.service_name }}:latest ${{ inputs.context_path }}
    
    - name: Log in to Docker Hub
      run: echo "${{ inputs.DOCKERHUB_PASS }}" | docker login -u "${{ inputs.DOCKERHUB_PASS }}" --password-stdin

    - name: Push Docker image
      run: docker push ${{ inputs.DOCKERHUB_USER }}/${{ inputs.service_name }}:latest
